- name: ML Server Configuration
  hosts: webserver
  gather_facts: false

- name: Update apt in Ubuntu
  ansible.builtin.import_playbook: playbooks/apt.yml

- name: Install Docker engine
  ansible.builtin.import_playbook: playbooks/docker.yml

- name: Clone GitHub repository
  ansible.builtin.import_playbook: playbooks/git-clone.yml

- name: Install Python3.9 and configure venv (virtual environment)
  ansible.builtin.import_playbook: playbooks/python3.9.yml

- name: Load .env files
  ansible.builtin.import_playbook: playbooks/configure_airflow_server_credentials.yml

- name: Configure PyPi server
  ansible.builtin.import_playbook: playbooks/pypi-server.yml

- name: Run docker containers (docker-compose file)
  ansible.builtin.import_playbook: playbooks/deploy_airflow_containers.yml

- name: Upload PyPi packages
- ansible.builtin.import_playbook: playbooks/upload_pypi_packages.yml
