- name: Configure Airflow server .env files with the credentials
  hosts: "*"
  become: true
  vars_files:
    - ../inventories/dev/group_vars/secrets.enc.yml

  tasks:
    - name: "Configure Airflow .env file with custom credentials"
      ansible.builtin.shell:
        cmd: echo "{{ item.key }}={{ item.value }}" | tee /home/ubuntu/Energy_Forecasting/src/airflow/.env -a
      loop:
        - { key: AIRFLOW_UID, value: $(id -u) }
        - { key: ML_PIPELINE_ROOT_DIR, value: /opt/airflow/dags }

    - name: Configure feature pipeline .env file
      ansible.builtin.shell:
        cmd: echo "{{ item.key }}={{ item.value }}" | tee /home/ubuntu/Energy_Forecasting/src/feature-pipeline/.env -a
      loop:
        - { key: FS_API_KEY, value: "{{ FS_API_KEY }}" }
        - { key: FS_PROJECT_NAME, value: "{{ FS_PROJECT_NAME }}" }
        - { key: WANDB_API_KEY, value: "{{ WANDB_API_KEY }}" }
        - { key: WANDB_ENTITY, value: "{{ WANDB_ENTITY }}" }
        - { key: WANDB_PROJECT, value: "{{ WANDB_PROJECT }}" }

    - name: Configure training pipeline .env file
      ansible.builtin.shell:
        cmd: echo "{{ item.key }}={{ item.value }}" | tee /home/ubuntu/Energy_Forecasting/src/training-pipeline/.env -a
      loop:
        - { key: FS_API_KEY, value: "{{ FS_API_KEY }}" }
        - { key: FS_PROJECT_NAME, value: "{{ FS_PROJECT_NAME }}" }
        - { key: WANDB_API_KEY, value: "{{ WANDB_API_KEY }}" }
        - { key: WANDB_ENTITY, value: "{{ WANDB_ENTITY }}" }
        - { key: WANDB_PROJECT, value: "{{ WANDB_PROJECT }}" }

    - name: Configure batch prediction pipeline .env file
      ansible.builtin.shell:
        cmd: echo "{{ item.key }}={{ item.value }}" | tee /home/ubuntu/Energy_Forecasting/src/batch-prediction-pipeline/.env -a
      loop:
        - { key: FS_API_KEY, value: "{{ FS_API_KEY }}" }
        - { key: FS_PROJECT_NAME, value: "{{ FS_PROJECT_NAME }}" }
        - { key: WANDB_API_KEY, value: "{{ WANDB_API_KEY }}" }
        - { key: WANDB_ENTITY, value: "{{ WANDB_ENTITY }}" }
        - { key: WANDB_PROJECT, value: "{{ WANDB_PROJECT }}" }
        - { key: AWS_ACCESS_KEY_ID, value: "{{ AWS_ACCESS_KEY_ID }}" }
        - { key: AWS_SECRET_ACCESS_KEY, value: "{{ AWS_SECRET_ACCESS_KEY }}" }
        - { key: AWS_BUCKET_NAME, value: "{{ AWS_BUCKET_NAME }}" }
