- name: Deploy Docker container with app-api, app-frontend and app-monitoring
  hosts: "*"
  become: true
  gather_facts: false
  tasks:
    - name: "Deploy Docker-Compose website container"
      ansible.builtin.command:
        chdir: /home/ubuntu/Energy_Forecasting/src/
        cmd: docker compose -f deploy/app-docker-compose.yml --project-directory . up -d --build

    # TODO: Run the docker container using ansible.builtin.docker_compose
    # - name: "Deploy container"
    #   ansible.builtin.docker_compose:
    #     project_src: /home/ubuntu/Energy_Forecasting/src/deploy/
    #     files: ["app-docker-compose.yml"]
    #     build: true
    #     state: present
