services:
  frontend:
    build:
      dockerfile: app-frontend/Dockerfile
    image: app-frontend:${APP_FRONTEND_VERSION:-latest}
    restart: always
    ports:
      - 8501:8501
    depends_on:
      - api
    networks:
      webserver_subnet:
        ipv4_address: 172.20.0.4

  monitoring:
    build:
      dockerfile: app-monitoring/Dockerfile
    image: app-monitoring:${APP_MONITORING_VERSION:-latest}
    restart: always
    ports:
      - 8502:8502
    depends_on:
      - api
    networks:
      webserver_subnet:
        ipv4_address: 172.20.0.5

  api:
    build:
      dockerfile: app-api/Dockerfile
    image: app-api:${APP_API_VERSION:-latest}
    restart: always
    volumes:
      - ./credentials:/app/src/credentials
    env_file:
      - app-api/.env
    ports:
      - 8001:8001
    networks:
      webserver_subnet:
        ipv4_address: 172.20.0.6

networks:
  webserver_subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
